#/*
#* Copyright (c) 2022 Gouvernement du Québec
#* Auteur: Julio Cesar Torres 
#* SPDX-License-Identifier: LiLiQ-R-v.1.1
#* License-Filename: /LICENSE
#*/
##############################################################
# Requetes http pour l'émeteur d'attestations d'accès virtuel
##############################################################
# Avant usage, il faut renseigner les champs X-API-Key des 
# endpoints qui seront utilisés. 
# 
### Définition des variables globales 
# @hostname = http://localhost:3001
@hostname = https://exp-port-e-url-courte.apps.exp.openshift.cqen.ca
@id = 1
@short = "IsOboFA6"
# ============================================================================
#    Entity: short-url
#    Endpoint: /short-url
# ============================================================================

####
#### Redireciona ao url 
#### 
GET {{hostname}}/{{short}} HTTP/1.1
X-API-Key: 
Content-Type: application/json

####
#### Selects all short-url 
#### 
GET {{hostname}}/v1/short-url HTTP/1.1
X-API-Key: 
Content-Type: application/json

####
#### Selects a short-url 
#### 
GET {{hostname}}/v1/short-url/unique/{{short}} HTTP/1.1
X-API-Key: 
Content-Type: application/json

####
#### Create a new short-url 
#### 
POST {{hostname}}/v1/short-url HTTP/1.1
X-API-Key: 
Content-Type: application/json

{
    "originalUrl": "https://exp-port-e-consommateur-agent.apps.exp.openshift.cqen.ca?c_i=eyJAdHlwZSI6ICJkaWQ6c292OkJ6Q2JzTlloTXJqSGlxWkRUVUFTSGc7c3BlYy9jb25uZWN0aW9ucy8xLjAvaW52aXRhdGlvbiIsICJAaWQiOiAiODgzZWZkZTAtNmFmYi00YjQ5LWE5MDAtMTIyMmY4NzQ5OGQ1IiwgImxhYmVsIjogIkNvbnNvbW1hdGV1ciBwaHlzaXF1ZSBwb3VyIGF0dGVzdGF0aW9uIG51bVx1MDBlOXJpcXVlIiwgInJlY2lwaWVudEtleXMiOiBbIkY3VFRBOEhoUkFYWlY0dFhmY2dwblpGUmlkQmdGUmtYQkxRTVBlREdYMlphIl0sICJzZXJ2aWNlRW5kcG9pbnQiOiAiaHR0cHM6Ly9leHAtcG9ydC1lLWNvbnNvbW1hdGV1ci1hZ2VudC5hcHBzLmV4cC5vcGVuc2hpZnQuY3Flbi5jYSJ9",
    "uniqueId": "", 
    "numberClicks": 0, 
    "user": "port-e-user"
}

####
DELETE {{hostname}}/v1/short-url/{{id}} HTTP/1.1
X-API-Key: 
Content-Type: application/json



@access-id=1
@ngrokadress=https://f46b-107-159-197-196.ngrok.io

# Endpoint temporaire entree acces/refus
####
PATCH {{hostname}}/v1/short-url/{{access-id}} HTTP/1.1
X-API-Key: 
Content-Type: application/json

{
    "originalUrl": "nouveaucrm/webhook/accept"
}
